<a href="https://colab.research.google.com/github/Glodintec23/DS-ML/blob/main/glodin_joseph_StudentCopy_of_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# program to create an array of all the even integers from 20 to 80
import numpy as np
x=np.arange(start=20,stop=80,step=2)
print(x)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [ ]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
import numpy as np
x=np.array([23,24,25,26,27,24,25,26,2,8,88,100])
y=np.array([12,45,78,23,27,24,36,12,45,78,100,88])
print("/n array1")
print(x)
print("/n array2")
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

/n array1
[ 23  24  25  26  27  24  25  26   2   8  88 100]
/n array2
[ 12  45  78  23  27  24  36  12  45  78 100  88]
[ True False False  True False False False  True False False False  True]
[ True False False  True  True  True False  True False False False  True]
[False  True  True False False False  True False  True  True  True False]
[False  True  True False  True  True  True False  True  True  True False]


In [ ]:
#program to multiply two given arrays of same size
import numpy as np
a1=np.array([[2,3,4],[4,5,6]])
a2=np.array([[7,8,9],[9,6,3]])
print(a1)
print(a2)
print("/n multiple")
print(np.multiply(a1,a2))

[[2 3 4]
 [4 5 6]]
[[7 8 9]
 [9 6 3]]
/n multiple
[[14 24 36]
 [36 30 18]]


In [ ]:
#Program to save a given array to a text file and load it
import numpy as np
import os
x=np.arange(64).reshape(8,8)
print("/n array")
print(x)
a='cl1  cl2  cl3  cl4'
np.savetxt('arrayfile.txt',x,fmt="%f",header=a)
print("/n after loading content")
print(np.loadtxt('arrayfile.txt'))


/n array
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
/n after loading content
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29. 30. 31.]
 [32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47.]
 [48. 49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62. 63.]]
